name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to Staging
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          echo "Starting deployment to staging..."
          ssh -T -o BatchMode=yes -p $SSH_PORT $DEPLOY_USER@$SERVER_IP
          if [ $? -eq 0 ]; then
            echo "Deployment completed successfully"
          else
            echo "Deployment failed"
            exit 1
          fi

      - name: Verify Deployment
        if: success()
        run: |
          echo "Deployment to staging was successful"
          echo "You may want to manually verify the changes at https://staging.nierto.com"

      - name: Deployment Failed
        if: failure()
        run: |
          echo "Deployment to staging failed"
          echo "Please check the server logs for more information"